---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /docker/slskd/app:/app
      - /mnt/storage_box/media:/media
    restart: always
    networks:
      - npm_net
networks:
  npm_net:
    external: true